### PR TITLE
#2 Added prettier to the project

### LINKED ISSUE #2: [Improve] - Add prettier to the project
### Improvements:
- [ ] Add `prettier` to this project to make the code formatting easy fro other developers
- [ ] Add relevant scripts to `package.json` for easy access to prettier commands

Here are steps to add prettier to Node projects, you can refer this article:
https://blog.bitsrc.io/add-prettier-to-your-project-d7e91ac03d05

> ***Note:*** Make sure to format all the files as well using prettier

### PR DESCRIPTION
**Pull request by jeroenekkelkamp**
Fixes #2 
Added prettier to the project. Also added an prettierignore so that folders like node_modules are skipped in the check.

To use prettier simply use one of the following npm commands.

`npm run check-formatting` This checks which files are not properly formatted.
`npm run format` This formats all files not in the .prettierignore and not properly formatted

### CODE REVIEW

**Comment by gurpreet-legend** [comment]
@jeroenekkelkamp , have you formatted all the files, like running the scripts for all the `.js` files? Because I don't see any changes except the `package.json` and creation of `.prettierrc` and `.prettierignore`

Make sure you run the scripts for all the `.js` files at least and then I'll merge the PR :)

**Comment by jeroenekkelkamp** [comment]
@gurpreet-legend you're right, i forgot to run the linter, should be all good now :D

**Comment by jeroenekkelkamp** [comment]
@gurpreet-legend Have you had time to check this pr?

**Comment by gurpreet-legend** [comment]
@jeroenekkelkamp , great!

**Pull request merged**
